workflows:
  ios-release-workflow:
    name: iOS IPA Build (No Codesign)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        # 你可以在此处添加 SHOREBIRD_TOKEN，或者保持在 Codemagic UI 中设置
        SHOREBIRD_TOKEN: eyJyZWZyZXNoX3Rva2VuIjoiMS8vMDY1SEZ2XzBTa3h6T0NnWUlBUkFBR0FZU053Ri1MOUlyVmM2aXF2TjFNTmhyVHhTRi1LVlByZkhnTzR6TFVfblVqQlFpaVpTNkdRU2VYcEpxbC1nZDdsTVpWTGk3S19qb3pMZyIsImF1dGhfcHJvdmlkZXIiOiJnb29nbGUifQ==
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build and Package IPA
        script: |
          # 1. 改用 build ios 生成 .app
          # 显式禁止签名，并捕获错误
          flutter build ios --release --no-codesign --build-number=$(git rev-list --count HEAD) --build-name="1.0.$(git rev-list --count HEAD)" || { echo "❌ Flutter Build Failed"; exit 1; }
          
          # 2. 创建 Payload
          mkdir -p build/ios/ipa/Payload
          
          # 3. 全局查找 .app 文件
          echo "Looking for .app file in build/ios..."
          APP_PATH=$(find build/ios -name "*.app" -type d | head -n 1)
          
          if [ -z "$APP_PATH" ]; then
            echo "❌ Error: .app file not found!"
            echo "Listing build directory:"
            ls -R build/ios
            exit 1
          fi
          
          echo "✅ Found app at: $APP_PATH"
          cp -r "$APP_PATH" build/ios/ipa/Payload/
          
          # 4. 压缩
          cd build/ios/ipa
          zip -r juhemusic.ipa Payload
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - zhaozheng982@gmail.com
