workflows:
  ios-release-workflow:
    name: iOS IPA Build (No Codesign)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        # 你可以在此处添加 SHOREBIRD_TOKEN，或者保持在 Codemagic UI 中设置
        SHOREBIRD_TOKEN: eyJyZWZyZXNoX3Rva2VuIjoiMS8vMDY1SEZ2XzBTa3h6T0NnWUlBUkFBR0FZU053Ri1MOUlyVmM2aXF2TjFNTmhyVHhTRi1LVlByZkhnTzR6TFVfblVqQlFpaVpTNkdRU2VYcEpxbC1nZDdsTVpWTGk3S19qb3pMZyIsImF1dGhfcHJvdmlkZXIiOiJnb29nbGUifQ==
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build and Package IPA
        script: |
          # 1. 强制禁用 Xcode 自动签名 (这是导致 "Build requires Development Team" 的根源)
          echo "Patching project.pbxproj to disable signing..."
          find ios -name "project.pbxproj" -exec sed -i '' 's/CODE_SIGN_STYLE = Automatic;/CODE_SIGN_STYLE = Manual;/g' {} +
          find ios -name "project.pbxproj" -exec sed -i '' 's/"CODE_SIGN_IDENTITY\[sdk=iphoneos\*\]" = "iPhone Developer";/"CODE_SIGN_IDENTITY[sdk=iphoneos*]" = "";/g' {} +
          find ios -name "project.pbxproj" -exec sed -i '' 's/CODE_SIGNING_REQUIRED = YES;/CODE_SIGNING_REQUIRED = NO;/g' {} +
          find ios -name "project.pbxproj" -exec sed -i '' 's/CODE_SIGNING_ALLOWED = YES;/CODE_SIGNING_ALLOWED = NO;/g' {} +
          
          # 2. 运行构建命令
          flutter build ios --release --no-codesign || { echo "❌ Flutter Build Failed"; exit 1; }
          
          # 3. 创建 Payload
          mkdir -p build/ios/ipa/Payload
          
          # 3. 全局查找 .app 文件
          echo "Looking for .app file in build/ios..."
          APP_PATH=$(find build/ios -name "*.app" -type d | head -n 1)
          
          if [ -z "$APP_PATH" ]; then
            echo "❌ Error: .app file not found!"
            echo "Listing build directory:"
            ls -R build/ios
            exit 1
          fi
          
          echo "✅ Found app at: $APP_PATH"
          cp -r "$APP_PATH" build/ios/ipa/Payload/
          
          # 4. 压缩
          cd build/ios/ipa
          zip -r juhemusic.ipa Payload
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - zhaozheng982@gmail.com
